### PR TITLE
Issue/2

### LINKED ISSUE #2: Initial structuring of repository
Setting up the "skeleton" for the repository -- folders, files, etc. -- based off of the existing `h0rton` repository.

### PR DESCRIPTION
**Pull request by rodrigo-castellon**
Set up general structure and renamed folders to exconvnet (to be completed on base repository).

Closes #2

### CODE REVIEW

**Comment by rodrigo-castellon** [comment]
Or would you like to merge the commits into a new branch `issue/2`??

**Comment by jiwoncpark** [comment]
So far so good! I expect you'll keep making changes in this PR?

**Comment by rodrigo-castellon** [comment]
I believe that the things I explained in Issue #2 have been resolved. So merge this pull request and move on to another one later?

**Comment by jiwoncpark** [comment]
Up to you. Either way sounds good.

**Pull request merged**
